apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.edgex_device_mqtt.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    io.kompose.service: {{ .Values.edgex_device_mqtt.name }}
spec:
  ports:
    - port: {{ .Values.edgex_device_mqtt.port }}
  selector:
    io.kompose.service: {{ .Values.edgex_device_mqtt.name }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    io.kompose.service: {{ .Values.edgex_device_mqtt.name }}
  name: {{ .Values.edgex_device_mqtt.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.edgex_device_mqtt.name }}
  minReplicas: {{ .Values.global.hpa.min }}
  maxReplicas: {{ .Values.global.hpa.max }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.global.hpa.metric }}
      targetAverageUtilization: {{ .Values.global.hpa.utilization }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.edgex_device_mqtt.name }}
  name: {{ .Values.edgex_device_mqtt.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.edgex_device_mqtt.name }}
    spec:
      containers:
      - image: {{ .Values.deviceMqttImage }}
        name: {{ .Values.edgex_device_mqtt.name }}
        ports:
        - containerPort: {{ .Values.edgex_device_mqtt.port }}
        resources: {}
        volumeMounts:
        - mountPath: {{ .Values.volumes.logs.mountPath }}
          name: {{ .Values.volumes.logs.name }}
      restartPolicy: Always
      volumes:
      - name: {{ .Values.volumes.logs.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.logs.claimName }}

