apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  ports:
  - name: "8125"
    port: 8125
    targetPort: 8125
  type: ClusterIP
  selector:
    io.kompose.service: telegraf
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: telegraf
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: telegraf-configmap
      - name: telegraf-utmp
        hostPath:
          path: /run/utmp
      containers:
      - image: telegraf:alpine
        name: telegraf
        ports:
        - containerPort: 8125
        resources: {}
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: configmap-volume
          subPath: telegraf.conf
        - mountPath: /var/run/utmp
          name: telegraf-utmp
          readOnly: true
      restartPolicy: Always

